name: "test"

on:
  push:
    branches: [main]
  schedule:
    - cron: '*/10 * * * *'  # every 10 minutes
  workflow_dispatch: # manual trigger

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          windows-latest,
          macos-latest,
        ]
    
    env:
      Solution_Name: "Test.sln"

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Initialize dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x    

    - name: Restore
      run: dotnet restore "${{ env.Solution_Name }}"

    - name: Build
      run: |
        dotnet build "${{ env.Solution_Name }}" --configuration Release --no-restore        

# TODO TEST
