name: "test"

on:
  push:
    branches: [main]
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes

jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [
          ubuntu-22.04,
          ubuntu-20.04,
          ubuntu-18.04,
          windows-latest,
          windows-2022,
          windows-2019,
          macos-latest,
          macos-15,
          macos-14,
          macos-13
        ]
    
    env:
      Solution_Name: "Test.sln"

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Initialize dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x    

    - name: Restore
      run: dotnet restore "${{ env.Solution_Name }}"

    - name: Build
      run: |
        dotnet build "${{ env.Solution_Name }}" --configuration Release --no-restore        

# TODO TEST